name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build Backend Image
      run: |
        docker build -t cloudmart-backend:latest ./applications/backend
        docker tag cloudmart-backend:latest dtlnguyen/cloudmart-backend:latest

    - name: Build Frontend Image
      run: |
        docker build -t cloudmart-frontend:latest ./applications/frontend
        docker tag cloudmart-frontend:latest dtlnguyen/cloudmart-frontend:latest

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Images
      run: |
        docker push dtlnguyen/cloudmart-backend:latest
        docker push dtlnguyen/cloudmart-frontend:latest

    - name: Deploy Backend to ACI
      run: |
        az container create \
          --resource-group Student-RG-1902327 \
          --name cloudmart-backend \
          --image dtlnguyen/cloudmart-backend:latest \
          --ports 8000 \
          --restart-policy Always \
          --environment-variables COSMOS_ENDPOINT=${{ secrets.COSMOS_ENDPOINT }} COSMOS_KEY=${{ secrets.COSMOS_KEY }} \
          --query "provisioningState"

    - name: Deploy Frontend to ACI
      run: |
        az container create \
          --resource-group Student-RG-1902327 \
          --name cloudmart-frontend \
          --image dtlnguyen/cloudmart-frontend:latest \
          --ports 80 \
          --restart-policy Always \
          --environment-variables VITE_BACKEND_URL="http://cloudmart-backend:8000"
